public class MathematicalClass {
    //create 4 methods with two integer numbers
    public integer add(integer a, integer b){
        integer sum = a + b;
        return sum;
    }
    public integer substract(integer a, integer b){
        integer subst = a - b;
        return subst;
    }
    public integer multiply(integer a, integer b){
        integer mult = a*b;
        return mult;
    }
    public integer divide(integer a , integer b){
        integer div = a/b;
        return div;
    }
}
