system.debug('developer Console ILK MESAJI');
string firstName = 'Eva';
string lastName = 'JONES';
string fullName = firstName + ' ' + lastName;
system.debug(fullName);


string brand = 'VOLVO';
system.debug(brand);
string model = 'XC60';
system.debug(model);
string color = 'white';
system.debug(color);
string myCar = 'May car is' + ' ' + color + ' ' + brand + ' ' + model + '.' 
+ 'And I want to work as a salesforce Developer in VOLVO Group:)';
system.debug(myCar);