SoqlDemo.accountSoql_1();
SoqlDemo.accountSoql_2();

SoqlDemo.accountSoql_3();

SoqlDemo.accountSoql_4();


1- select id, name, phone, account.name, account.industry from contact where account.industry = 'Energy'
2-select id, name, subject__c, priority__c, Salesforce_project__r.project_name__c, salesforce_project__r.status__c from Salesforce_ticket__c



SoqlDemo2.childToParent_Soql1();

SoqlDemo2.sampleSogl4();

AccountInfo.showAccounts();